// Проверка бота без Telegram и Cloudflare: node test-worker.mjs
import worker from "./worker.js";
const calls = [];
globalThis.fetch = async (u, o) => { calls.push({ method: u.split("/").pop(), body: JSON.parse(o.body) }); return { json: async () => ({ ok: true }) }; };
const env = { BOT_TOKEN: "123:abc", APP_URL: "https://example.github.io/tabel/", WEBHOOK_SECRET: "s3cret_s3cret_s3cret", AUTHOR_TG: "nikita" };
let pass = 0, fail = 0;
const ok = (n, c, x) => { c ? (pass++, console.log("  ✓ " + n)) : (fail++, console.log("  ✗ " + n + (x ? "  → " + x : ""))); };
const hook = (msg, secret = env.WEBHOOK_SECRET) => worker.fetch(new Request("https://bot.example.workers.dev/hook", { method: "POST", headers: { "X-Telegram-Bot-Api-Secret-Token": secret }, body: JSON.stringify({ message: msg }) }), env);
const pm = (text) => ({ chat: { id: 42, type: "private" }, from: { first_name: "Анна" }, text });

calls.length = 0; let r = await hook(pm("/start"));
ok("/start: ответ 200 для Telegram", r.status === 200);
ok("/start: приветствие по имени", calls[0] && calls[0].body.text.startsWith("Привет, Анна!"), calls[0] && calls[0].body.text.slice(0, 40));
const btn = calls[0].body.reply_markup.inline_keyboard[0][0];
ok("/start: кнопка «Открыть Табель» открывает приложение", btn.text === "Открыть Табель" && btn.web_app.url === env.APP_URL);
calls.length = 0; await hook(pm("/start ref_school"));
ok("/start с параметром тоже приветствует", calls[0] && calls[0].body.text.includes("«Табель»"));
calls.length = 0; await hook(pm("/help"));
ok("/help: инструкция и ник автора", calls[0] && calls[0].body.text.includes("Как пользоваться") && calls[0].body.text.includes("@nikita"));
calls.length = 0; await hook(pm("привет, а как добавить ученика?"));
ok("любой текст: подсказка и кнопка", calls[0] && calls[0].body.text.includes("/help") && calls[0].body.reply_markup);
calls.length = 0; await hook({ chat: { id: -1, type: "group" }, text: "/start" });
ok("в группах молчит", calls.length === 0);
calls.length = 0; r = await hook(pm("/start"), "wrong");
ok("чужой запрос без секрета отклоняется", r.status === 403 && calls.length === 0);
calls.length = 0; r = await worker.fetch(new Request("https://bot.example.workers.dev/setup?key=nope"), env);
ok("настройка без ключа запрещена", r.status === 403 && calls.length === 0);
calls.length = 0; r = await worker.fetch(new Request("https://bot.example.workers.dev/setup?key=" + env.WEBHOOK_SECRET), env);
const sw = calls.find(c => c.method === "setWebhook");
ok("настройка: вебхук на /hook с секретом", r.status === 200 && sw && sw.body.url === "https://bot.example.workers.dev/hook" && sw.body.secret_token === env.WEBHOOK_SECRET);
ok("настройка: меню команд /start и /help", calls.some(c => c.method === "setMyCommands" && c.body.commands.length === 2));
r = await worker.fetch(new Request("https://bot.example.workers.dev/setup?key=" + env.WEBHOOK_SECRET), { ...env, APP_URL: "example.com" });
ok("подскажет, если адрес приложения без https", r.status === 500 && (await r.text()).includes("https://"));
r = await worker.fetch(new Request("https://bot.example.workers.dev/setup?key=" + env.WEBHOOK_SECRET), { ...env, APP_URL: "https://github.com/3tringleee/tabel" });
ok("адрес репозитория вместо сайта — понятная подсказка, куда смотреть", r.status === 500 && (await r.text()).includes("Settings → Pages"));
r = await worker.fetch(new Request("https://bot.example.workers.dev/setup?key=" + env.WEBHOOK_SECRET), env);
ok("после настройки показывает, куда ведёт кнопка", (await r.text()).includes(env.APP_URL));
console.log(fail ? `\nПРОВАЛЕНО: ${fail}` : `\nБот: все проверки пройдены (${pass})`);
process.exit(fail ? 1 : 0);
